name: integrate
on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  php-70-zts:
    name: "PHP-7.0-ZTS"
    env:
      PHP: "7.0"
      enable_debug: "yes"
      enable_maintainer_zts: "yes"
      enable_session: "yes"
      TEST_PHP_ARGS : "--show-diff"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install
        run: |
          sudo apt-get install -y \
            php-cli \
            php-pear \
            re2c
      - name: Prepare
        run: |
            phpize
      - name: Build
        run: |
            ./confgiure
      - name: Make
        run: |
            make
      - name: Test
        run: |
            make test

